mySite/mySite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

app_name = "polls"

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls', namespace="polls")),
]

mySite/polls/urls.py
from django.conf.urls import url
from . import views

app_name = "polls"

urlpatterns = [

    url(r'^$', views.index, name="index"),
    #127.0.0.1:8000/polls
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name="detail"),
    #127.0.0.1:8000/polls/2
    url(r'^(?P<question_id>[0-9]+)/results$', views.results, name="results"),
    #127.0.0.1:8000/polls/2/results
    url(r'^(?P<question_id>[0-9]+)/vote$', views.vote, name="vote"),
    # 127.0.0.1:8000/polls/2/vote
]

mySite/polls/models.py
from django.db import models

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("Date published")

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    choice_text= models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.choice_text

mySite/polls/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question
from django.shortcuts import get_object_or_404
from django.urls import reverse
# Create your views here.


def index(request):
    latest_questions = Question.objects.order_by('-pub_date')[:5]
    return render(request, "polls/index.html", {'latest_questions': latest_questions})


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except:
        return render(request, "polls/detail.html", {"question": question, 'error_message': "Please select a choice"})
    else:
        selected_choice.votes +=1
        selected_choice.save()

        return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

mySite/polls/templates/polls/base.html
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}"/>
</head>
<body>
<p>Header</p>

{% include "polls/header.html" %}

<div class="jumbotron">
      <div class="container">
            <h1> Django Poll App!</h1>
            <!--block and include help us reuse our code -->
            {% block main_content %}
            {% endblock %}

            {% include 'polls/footer.html' %}
      </div>
</div>


</body>
</html>

mySite/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block main_content %}

<h1>{{question.question_text}}</h1>

{% if error_message %} <p><strong>{{error_message}}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}"/>
        <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
    {% endfor %}
    <input type="submit" class="btn btn-success"value="vote"/>

</form>
    <a href="{% url 'polls:index' %}"><-- Back to Question List</a>
{% endblock %}

mySite/polls/templates/polls/footer.html
<footer>
        <p>&copy; 2016 Company, Inc.</p>
      </footer>

mySite/polls/templates/polls/header.html
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

mySite/polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block main_content %}

<h1> Please Choose a Question.</h1>

{% if latest_questions %}
    <ul>
        {% for question in latest_questions %}
            <li><a href = '/polls/{{question.id}}'><b>{{question.question_text}}</b></a></li>
        {% endfor %}
    </ul>
{% else %}
    <p> You need to add some questions</p>
{% endif %}


{% endblock %}

mySite/polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block main_content %}

<h1> {{question.question_text}} </h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li> {{choice.choice_text}} -- {{choice.votes}} vote {{ choice.votes|pluralize}}</li>
    {% endfor %}

</ul>

<a href = "{% 'polls:detail' question.id}">Vote again</a>

{% endblock %}